services:
  nextjs-app:
    build:
      context: ./jone-piece/jone-piece
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://${DOMAIN_NAME_JONE_API}
    container_name: nextjs-app
    restart: always
    environment:
      - NODE_ENV=production
      - API_URL=http://jonepiece-api:4000/jone-piece
      - NEXT_PUBLIC_API_URL=https://${DOMAIN_NAME_JONE_API}
    volumes:
      - ${JONE_PIECE_MEDIA_DIR}/caps_en:/app/public/caps_en
      - ${JONE_PIECE_MEDIA_DIR}/One_Piece_Colored:/app/public/One_Piece_Colored
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.jone.rule=Host(`${DOMAIN_NAME_JONE}`)
      - traefik.http.routers.jone.entrypoints=web,websecure
      - traefik.http.routers.jone.tls=true

networks:
  traefik:
    external: true
